bot:
  name: NAMEBOT
  token: TOKENBOT
spring:
  datasource:
    url: jdbc:postgresql://{Host}:{Port}/{Database}?user={User}&password={Password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
